create table if not exists public.orders (
  id text primary key,
  table_no text not null,
  customer_name text not null default 'Pelanggan',
  payment_method text not null default 'cash',
  payment_status text not null default 'pending',
  order_status text not null default 'baru',
  items jsonb not null default '[]'::jsonb,
  note text default '',
  total_amount integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  item_name text not null,
  qty integer not null default 1,
  unit_price integer not null default 0,
  subtotal integer not null default 0,
  image_url text default '',
  sort_order integer not null default 1,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "orders can be read by app" on public.orders;
create policy "orders can be read by app"
on public.orders for select
to anon
using (true);

drop policy if exists "orders can be created by buyer" on public.orders;
create policy "orders can be created by buyer"
on public.orders for insert
to anon
with check (true);

drop policy if exists "orders can be updated by app" on public.orders;
create policy "orders can be updated by app"
on public.orders for update
to anon
using (true)
with check (true);

drop policy if exists "order items can be read by app" on public.order_items;
create policy "order items can be read by app"
on public.order_items for select
to anon
using (true);

drop policy if exists "order items can be created by buyer" on public.order_items;
create policy "order items can be created by buyer"
on public.order_items for insert
to anon
with check (true);

do $$
begin
  alter publication supabase_realtime add table public.orders;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.order_items;
exception
  when duplicate_object then null;
end $$;
